// UIFileHelper — CRUD for .uxml and .uss asset files.
// Called exclusively from CommandRouter.MediaHandlers.ExecUitkFile.
// Surgical edit helpers (set-attr, add-class, set-rule…) are in UIFileHelper.Uxml.cs
// and UIFileHelper.Uss.cs (partial class split per PHASE3 design).
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace UnityMCP.Editor
{
    public static partial class UIFileHelper
    {
        // Testability seam — tests can inject a call spy. Shared by Uxml.cs and Uss.cs.
        internal static Action<string, ImportAssetOptions> _importAsset =
            AssetDatabase.ImportAsset;

        // C2: in-memory backup store — cleared on domain reload (CLR restart).
        private static readonly Dictionary<string, string> _fileBackups = new();

        // USS forbidden patterns (pre-write validation).
        private static readonly (string Pattern, string Label)[] _ussForbidden =
        {
            (@"display\s*:\s*grid",              "display: grid"),
            (@"@media",                          "@media queries"),
            (@"calc\s*\(",                       "calc()"),
            (@":nth-child",                      ":nth-child"),
            (@"@keyframes",                      "@keyframes"),
            (@"linear-gradient|radial-gradient", "CSS gradients"),
        };

        // ── PUBLIC API ──────────────────────────────────────────────────────

        public static string ReadUIFile(string assetPath)
        {
            var abs = ToAbsPath(assetPath, out var err);
            if (err != null) return err;
            if (!File.Exists(abs)) return $"err: file not found: {assetPath}";
            return File.ReadAllText(abs, JsonHelper.Utf8NoBom);
        }

        // action: "write" | "create_uxml" | "create_uss"
        public static string WriteUIFile(string assetPath, string action, string content)
            => WriteUIFile(
                assetPath,
                action,
                content,
                path => AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(path),
                path => AssetDatabase.LoadAssetAtPath<StyleSheet>(path));

        // Loader parameters keep post-import failure paths deterministic in tests without
        // introducing mutable global seams. Production always uses AssetDatabase loaders.
        internal static string WriteUIFile(string assetPath, string action, string content,
            Func<string, VisualTreeAsset> loadVisualTreeAsset,
            Func<string, StyleSheet> loadStyleSheet)
        {
            var abs = ToAbsPath(assetPath, out var err);
            if (err != null) return err;

            bool isNew = !File.Exists(abs);
            var warn = isNew ? "" : "warn: file may be open in UI Builder — save in UI Builder first to avoid losing unsaved changes.\n";

            if (action == "create_uxml") content ??= MinimalUxmlTemplate();
            else if (action == "create_uss") content ??= "/* Generated by Unity Biome MCP */\n";
            else if (content == null) return "err: content is required for action=write";

            bool isUxml = assetPath.EndsWith(".uxml", StringComparison.OrdinalIgnoreCase);
            var preErr = isUxml ? ValidateUxmlContent(content) : ValidateUssContent(content);
            if (preErr != null) return preErr;

            // Idempotency: skip if unchanged
            if (File.Exists(abs) && NormalizeForComparison(content) == NormalizeForComparison(File.ReadAllText(abs, JsonHelper.Utf8NoBom)))
                return "no-op: content unchanged";

            // A path recreated after an external deletion must not inherit an old in-memory
            // backup. On failed validation this invocation owns the new file and removes it.
            if (isNew) _fileBackups.Remove(abs);
            else BackupFile(abs);
            Directory.CreateDirectory(Path.GetDirectoryName(abs)!);
            File.WriteAllText(abs, content, JsonHelper.Utf8NoBom); // C4: no BOM; C2: in-place

            _importAsset(assetPath, ImportAssetOptions.Default);

            if (isUxml)
            {
                var valErr = ValidateImportedUxml(
                    abs, assetPath, isNew, loadVisualTreeAsset);
                if (valErr != null) return valErr;
                return $"{warn}ok: {action}\npath: {assetPath}\nvalidated: CloneTree OK{(isNew ? "\nnew-file: true" : "")}";
            }

            var ss = loadStyleSheet(assetPath);
            if (ss == null)
            {
                AutoRevert(abs, assetPath, isNew);
                return "err: USS import failed — auto-reverted.";
            }
            return $"{warn}ok: {action}\npath: {assetPath}{(isNew ? "\nnew-file: true" : "")}";
        }

        // Surgical edits — implementations in UIFileHelper.Uxml.cs / UIFileHelper.Uss.cs.
        public static string EditUIFile(string assetPath, string action,
            string selector, string attr, string value, string cssClass,
            string parent, string tag, string attrs, string prop)
        {
            var abs = ToAbsPath(assetPath, out var err);
            if (err != null) return err;
            if (!File.Exists(abs)) return $"err: file not found: {assetPath}";
            var warn = "warn: file may be open in UI Builder — save in UI Builder first to avoid losing unsaved changes.\n";

            return action switch
            {
                "set-attr"       => warn + UxmlSetAttr(abs, assetPath, selector, attr, value),
                "add-class"      => warn + UxmlAddClass(abs, assetPath, selector, cssClass),
                "remove-class"   => warn + UxmlRemoveClass(abs, assetPath, selector, cssClass),
                "add-element"    => warn + UxmlAddElement(abs, assetPath, parent, tag, attrs),
                "remove-element" => warn + UxmlRemoveElement(abs, assetPath, selector),
                "set-rule"       => warn + UssSetRule(abs, assetPath, selector, prop, value),
                "remove-rule"    => warn + UssRemoveRule(abs, assetPath, selector),
                _ => $"err: unknown action '{action}'. Surgical: set-attr add-class remove-class add-element remove-element set-rule remove-rule",
            };
        }

        public static string RevertUIFile(string assetPath)
        {
            var abs = ToAbsPath(assetPath, out var err);
            if (err != null) return err;
            if (!_fileBackups.TryGetValue(abs, out var backup))
                return "err: no backup available — domain was reloaded or no prior write in this session. Use git to recover.";
            File.WriteAllText(abs, backup, JsonHelper.Utf8NoBom);
            _importAsset(assetPath, ImportAssetOptions.Default);
            _fileBackups.Remove(abs);
            return $"ok: reverted\npath: {assetPath}";
        }

        // ── PATH GUARD (C5) ──────────────────────────────────────────────────

        internal static string ToAbsPath(string assetPath, out string err)
        {
            err = null;
            if (string.IsNullOrEmpty(assetPath))
                { err = "err: path is required"; return null; }
            if (!assetPath.StartsWith("Assets/", StringComparison.Ordinal))
                { err = $"err: path must start with 'Assets/', got: '{assetPath}'"; return null; }
            if (assetPath.Contains(".."))
                { err = "err: path must not contain '..'"; return null; }
            var abs = Path.GetFullPath(Path.Combine(Application.dataPath, "..", assetPath));
            if (!abs.StartsWith(Application.dataPath, StringComparison.Ordinal))
                { err = $"err: resolved path escapes Assets/: {abs}"; return null; }
            return abs;
        }

        // ── BACKUP ────────────────────────────────────────────────────────────

        internal static void BackupFile(string absPath)
        {
            if (File.Exists(absPath))
                _fileBackups[absPath] = File.ReadAllText(absPath, JsonHelper.Utf8NoBom);
        }

        internal static void AutoRevert(string absPath, string assetPath,
            bool createdThisCall = false)
        {
            if (createdThisCall)
            {
                _fileBackups.Remove(absPath);
                AssetDatabase.DeleteAsset(assetPath);
                if (File.Exists(absPath)) File.Delete(absPath);
                if (File.Exists(absPath + ".meta")) File.Delete(absPath + ".meta");
                AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
                return;
            }

            if (!_fileBackups.TryGetValue(absPath, out var backup)) return;
            File.WriteAllText(absPath, backup, JsonHelper.Utf8NoBom);
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
        }

        // ── VALIDATION ────────────────────────────────────────────────────────

        internal static string ValidateUxmlContent(string content)
        {
            try
            {
                var doc = XDocument.Parse(content);
                if (doc.Root == null) return "err: UXML has no root element";
            }
            catch (Exception ex) { return $"err: invalid XML: {ex.Message}"; }
            return null;
        }

        internal static string ValidateImportedUxml(string absPath, string assetPath,
            bool createdThisCall = false,
            Func<string, VisualTreeAsset> loadVisualTreeAsset = null)
        {
            loadVisualTreeAsset ??= path => AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(path);
            var vta = loadVisualTreeAsset(assetPath);
            if (vta == null) { AutoRevert(absPath, assetPath, createdThisCall); return "err: UXML import failed (asset null) — auto-reverted. Check get_console for [UXML Import Error]."; }
            if (vta.CloneTree() == null) { AutoRevert(absPath, assetPath, createdThisCall); return "err: UXML import failed (CloneTree null) — auto-reverted. Check get_console for [UXML Import Error]."; }
            return null;
        }

        internal static string ValidateUssContent(string content)
        {
            foreach (var (pat, label) in _ussForbidden)
                if (Regex.IsMatch(content, pat, RegexOptions.IgnoreCase))
                    return $"err: unsupported USS feature: {label}. See Unity USS docs.";
            return null;
        }

        // ── SHARED ────────────────────────────────────────────────────────────

        internal static string NormalizeForComparison(string content)
            => Regex.Replace(content.Replace("\r\n", "\n"), @"[ \t]+", " ").Trim();

        internal static string MinimalUxmlTemplate() =>
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
            "<ui:UXML xmlns:ui=\"UnityEngine.UIElements\">\n" +
            "    <ui:VisualElement name=\"root\" />\n" +
            "</ui:UXML>\n";
    }
}
