"""Single source of truth for tool metadata (M8).

Every MCP tool + a handful of protocol-level commands (category='_INTERNAL':
ping/get_version/export_package/import_package — NOT MCP tools, contribute a
timeout only) get exactly one ToolSpec entry here. gating.py derives its
_CORE_TOOLS/_THEMED_CATEGORIES/TIER1/_ALL_KNOWN collections from this dict at
import time instead of hand-typing 4 separately-drifting literals.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class ToolSpec:
    """category: themed group key (e.g. "SCENE_EDIT"), "CORE", or "_INTERNAL"
    (protocol-level command, not an MCP tool — excluded from gating collections,
    contributes to timeouts only).
    core: always-visible + full-schema (see gating._CORE_TOOLS).
    tier1: always-visible but NOT core (themed tool promoted to Tier1).
    timeout_s: per-command TCP timeout; DEFAULT_TIMEOUT (30s) if unset."""
    category: str
    core: bool = False
    tier1: bool = False
    timeout_s: float = 30.0


DEFAULT_TIMEOUT: float = 30.0

_SPECS: dict[str, ToolSpec] = {
    'analyze_lod_culling': ToolSpec(category='RENDERING'),
    'animation': ToolSpec(category='ANIMATION'),
    'animator': ToolSpec(category='ANIMATION'),
    'animator_intent': ToolSpec(category='META'),
    'apply_template': ToolSpec(category='SESSION_SKILLS'),
    'ask': ToolSpec(category='CORE', core=True),
    'ask_user': ToolSpec(category='CORE', core=True, timeout_s=300.0),
    'asset': ToolSpec(category='ASSETS'),
    'auto_fix': ToolSpec(category='ADVANCED_CODE'),
    'auto_wire': ToolSpec(category='COMPONENTS'),
    'autofit_collider': ToolSpec(category='META'),
    'await_compile': ToolSpec(category='ADVANCED_CODE', tier1=True),
    'batch': ToolSpec(category='CORE', core=True, timeout_s=120.0),
    'budget_status': ToolSpec(category='META'),
    'check_colliders': ToolSpec(category='META'),
    'checkpoint': ToolSpec(category='ADVANCED_CODE'),
    'compile_preflight': ToolSpec(category='ADVANCED_CODE', tier1=True, timeout_s=60.0),
    'configure_objects': ToolSpec(category='META', tier1=True),
    'create_object': ToolSpec(category='CORE', core=True),
    'create_ui': ToolSpec(category='UI'),
    'debug': ToolSpec(category='DEBUG'),
    'debug_animator': ToolSpec(category='RUNTIME'),
    'debug_physics': ToolSpec(category='RUNTIME'),
    'delete_object': ToolSpec(category='CORE', core=True),
    'diagnose': ToolSpec(category='ADVANCED_CODE'),
    'discover_tools': ToolSpec(category='CORE', core=True),
    'do': ToolSpec(category='CORE', core=True),
    'doctor': ToolSpec(category='CORE', core=True),
    'editor': ToolSpec(category='CORE', core=True),
    'execute_code': ToolSpec(category='ADVANCED_CODE', timeout_s=60.0),
    'export_package': ToolSpec(category='_INTERNAL', timeout_s=120.0),
    'find_objects': ToolSpec(category='SCENE_EDIT'),
    'fingerprint': ToolSpec(category='SESSION_SKILLS', timeout_s=10.0),
    'fuzz_playtest': ToolSpec(category='UNIT_TESTS', tier1=True, timeout_s=300.0),
    'get_capabilities': ToolSpec(category='META'),
    'get_changes': ToolSpec(category='SESSION_SKILLS'),
    'get_compile_errors': ToolSpec(category='CORE', core=True),
    'get_component': ToolSpec(category='CORE', core=True),
    'get_components_list': ToolSpec(category='SCENE_EDIT'),
    'get_console': ToolSpec(category='CORE', core=True, timeout_s=10.0),
    'get_enabled_tools': ToolSpec(category='CORE', core=True),
    'get_frame_stats': ToolSpec(category='PROFILING'),
    'get_hierarchy': ToolSpec(category='CORE', core=True, timeout_s=15.0),
    'get_memory': ToolSpec(category='PROFILING'),
    'get_metrics': ToolSpec(category='DEBUG'),
    'get_object_detail': ToolSpec(category='SCENE_EDIT'),
    'get_perf': ToolSpec(category='RUNTIME'),
    'get_schema': ToolSpec(category='ADVANCED_CODE'),
    'get_selection': ToolSpec(category='SCENE_EDIT'),
    'get_spatial_context': ToolSpec(category='UI'),
    'get_test_count': ToolSpec(category='UNIT_TESTS', timeout_s=10.0),
    'get_test_results': ToolSpec(category='UNIT_TESTS', tier1=True),
    'get_version': ToolSpec(category='_INTERNAL', timeout_s=5.0),
    'get_watches': ToolSpec(category='DEBUG'),
    'import_package': ToolSpec(category='_INTERNAL', timeout_s=120.0),
    'inspect': ToolSpec(category='CORE', core=True),
    'invoke_method': ToolSpec(category='RUNTIME', tier1=True),
    'list_connections': ToolSpec(category='CORE', core=True),
    'list_skills': ToolSpec(category='SESSION_SKILLS'),
    'list_templates': ToolSpec(category='SESSION_SKILLS'),
    'load_session': ToolSpec(category='SESSION_SKILLS'),
    'manage_component': ToolSpec(category='CORE', core=True),
    'material': ToolSpec(category='SHADERS_MATERIAL'),
    'material_audit': ToolSpec(category='SHADERS_MATERIAL'),
    'menu': ToolSpec(category='ADVANCED_CODE'),
    'move_to': ToolSpec(category='RUNTIME', tier1=True),
    'navmesh_query': ToolSpec(category='META'),
    'object_diff': ToolSpec(category='SCENE_EDIT'),
    'particle': ToolSpec(category='ANIMATION'),
    'permission_prompt': ToolSpec(category='CORE', core=True),
    'ping': ToolSpec(category='_INTERNAL', timeout_s=5.0),
    'ping_object': ToolSpec(category='SCENE_EDIT'),
    'prefab': ToolSpec(category='ASSETS'),
    'profile': ToolSpec(category='PROFILING'),
    'project_settings': ToolSpec(category='ASSETS'),
    'query_state': ToolSpec(category='RUNTIME', tier1=True),
    'recompile': ToolSpec(category='ADVANCED_CODE'),
    'reconnect_unity': ToolSpec(category='CORE', core=True),
    'references': ToolSpec(category='SHADERS_MATERIAL'),
    'region_clear': ToolSpec(category='META'),
    'render_analyze': ToolSpec(category='RENDERING'),
    'resolve_tool_schema': ToolSpec(category='CORE', core=True),
    'run_playtest': ToolSpec(category='UNIT_TESTS', tier1=True, timeout_s=300.0),
    'run_tests': ToolSpec(category='UNIT_TESTS', tier1=True, timeout_s=300.0),
    'save_session': ToolSpec(category='SESSION_SKILLS'),
    'save_skill': ToolSpec(category='SESSION_SKILLS'),
    'save_template': ToolSpec(category='SESSION_SKILLS'),
    'scan_scene': ToolSpec(category='META'),
    'scene': ToolSpec(category='CORE', core=True),
    'scene_diff': ToolSpec(category='SESSION_SKILLS'),
    'scene_environment': ToolSpec(category='META'),
    'scene_health': ToolSpec(category='META'),
    'screenshot': ToolSpec(category='SCREENSHOTS', tier1=True),
    'screenshot_baseline': ToolSpec(category='SCREENSHOTS'),
    'screenshot_compare': ToolSpec(category='SCREENSHOTS'),
    'scriptable_object': ToolSpec(category='ASSETS'),
    'search_scene': ToolSpec(category='CORE', core=True, timeout_s=15.0),
    'set_active': ToolSpec(category='SCENE_EDIT'),
    'set_llm_config': ToolSpec(category='META'),
    'set_material': ToolSpec(category='SCENE_EDIT'),
    'set_parent': ToolSpec(category='CORE', core=True),
    'set_properties': ToolSpec(category='META', tier1=True),
    'set_property': ToolSpec(category='CORE', core=True),
    'set_property_delta': ToolSpec(category='SCENE_EDIT'),
    'set_rect': ToolSpec(category='UI'),
    'set_runtime_property': ToolSpec(category='RUNTIME', tier1=True),
    'setup_objects': ToolSpec(category='META', tier1=True),
    'shader': ToolSpec(category='SHADERS_MATERIAL'),
    'smart_build': ToolSpec(category='ADVANCED_CODE'),
    'snapshot': ToolSpec(category='DEBUG'),
    'spatial_query': ToolSpec(category='META'),
    'sync_unity': ToolSpec(category='ADVANCED_CODE', tier1=True),
    'test_step': ToolSpec(category='UNIT_TESTS', tier1=True),
    'timeline': ToolSpec(category='ANIMATION'),
    'transfer_object': ToolSpec(category='SCENE_EDIT'),
    'ui_intent': ToolSpec(category='UI'),
    'undo_last': ToolSpec(category='ADVANCED_CODE'),
    'unwire_event': ToolSpec(category='COMPONENTS'),
    'use_skill': ToolSpec(category='SESSION_SKILLS'),
    'validate_layout': ToolSpec(category='UI'),
    'validate_references': ToolSpec(category='ADVANCED_CODE'),
    'vfx_intent': ToolSpec(category='VFX'),
    'wait_until': ToolSpec(category='RUNTIME', tier1=True),
    'watch_add': ToolSpec(category='DEBUG'),
    'watch_clear': ToolSpec(category='DEBUG'),
    'watch_remove': ToolSpec(category='DEBUG'),
    'watch_reset': ToolSpec(category='DEBUG'),
    'wire_event': ToolSpec(category='COMPONENTS'),
}
